### ISSUE TITLE
Evaluate SipHash 1-3

### ISSUE THREAD

**Issue by tibbe** [haskell-unordered-containers/hashable#118]
Rust has switched from SipHash 2-4 to 1-3. The latter is faster, maybe fast enough to be the default for us, and seems to be equally secure. Some graphs for Rust: https://i.imgur.com/5dKecOW.jpg

**Comment by phadej** [comment]
SipHash requires starting seed. Have you an idea how to deal with that fact in `hashable`. Just have some preselected one? But that would diminish the security value of SipHash.

**Comment by tibbe** [comment]
All good questions. We tried various way to have a seed injected before, but none of them satisfactory. Also, I don't know what security properties (if any) SipHash offers with a known seed.

**Comment by codygman** [comment]
What about [murmurhash](https://sites.google.com/site/murmurhash/)?

**Comment by tibbe** [comment]
Murmur 2 & 3 have known bad collision behavior: https://131002.net/siphash/#at

**Comment by codygman** [comment]
@tibbe Hm, alright. Forgive my ignorance, but can you give an example of how that would effect someone using a hashmap in their Haskell program for O(1) lookups?

**Comment by phadej** [comment]
@codygman The O(1) operations are actually O(n) where n is a size of collision set. With good hash functions we don't have collisions, so n = 1. With bad collision behaviour, (e.g `hash _ = 0`) all operations degrade to O(N) linear scans (where N is the size of `HashMap`). In practice we have n = 1 almost always, but this is potentially a risk, google "hash table vulnerabilty collision" for more info.

**Comment by treeowl** [comment]
highwayhash claims to be secure (and there's been *some* work on demonstrating this), while being substantially faster than SipHash.

Handling *any* of the more secure hashing algorithms really properly for composite values seems to require some restructuring of the `Hashable` methods. The most natural approach would be something like this:

```haskell
data Key = ...
data HashState = ...

initialize :: Key -> HashState

globalKey :: Key
globalKey = unsafePerformIO $ get_some_randomness
{-# NOINLINE globalKey #-}

finalize :: HashState -> Hash

class Hashable a where
  mix :: HashState -> a -> HashState

  hashWithKey :: Key -> a -> Hash
  hashWithKey k a = finalize (mix (initialize k) a)
```

Using `mix` is likely to be pretty inefficient thanks to marshaling, scatter/gather, etc. `hashWithKey` could optimize some cases by serializing, passing through small values unchanged, etc.

**Comment by Mistuke** [comment]
Have you guys considered also supporting `xxhash`? A lot of use cases don't really care about hash flooding attacks and can benefit greatly from the high throughput of xxhash. Especially for smaller keys https://aras-p.info/blog/2016/08/09/More-Hash-Function-Tests/ has a nice writeup and comparison. His previous post also compares quality of the hash functions in more detail.

**Comment by hvr** [comment]
For reference, #28 is when this packaged switched to SipHash, and https://github.com/tibbe/unordered-containers/blob/master/docs/developer-guide.md documents the design considerations affecting the choice of hash functions

**Comment by Mistuke** [comment]
@hvr yeah a flag would do the trick nicely!

**Comment by fishtreesugar** [comment]
Go's map using a [hash algorithm base on CPU AES instructions](https://github.com/golang/go/blob/d90f0b920054e5e3fba981eea67fe092732a4376/src/runtime/alg.go#L311), and fallback to a [wyhash's variant (since 1.17)](https://github.com/golang/go/blob/master/src/runtime/hash64.go) when AES instructions not available

**Comment by phadej** [comment]
`wyhash` is interesting, as it has 64bit internal state, so doesn't have integration problems like siphash (which internal state is larger).

also, TIL about SMHasher: https://github.com/rurban/smhasher

**Comment by phadej** [comment]
We are now using `xxhash`, so SIphash is irrelevant
