### ISSUE TITLE
Generic1 default implementation

### ISSUE THREAD

**Issue by fakedrake** [haskell-unordered-containers/hashable#127]
Currently there is only a `Generic` automatic deriving mechanism, would it be possible to also have `Generic1`.

**Comment by RyanGlScott** [comment]
This isn't really a well formed question, as `Generic1` won't work well with a class like `Hashable`. `Hashable` takes types of kind `*`, but `Generic1` works with types of kind `* -> *`.

FWIW, the next version of `hashable` will include a [`Hashable1` class](https://github.com/tibbe/hashable/blob/a0c288eb89933accff6977abbc8df69e96d9b811/Data/Hashable/Class.hs#L240-L246), which will support automatic derivation for types that are instances of `Generic1`. Does that work for you?

**Comment by fakedrake** [comment]
Yes exactly. Is there a plan for when that version will be on hackage?

**Comment by RyanGlScott** [comment]
I dunno... ask @tibbe :)

**Comment by RyanGlScott** [comment]
This is now available from the `Data.Hashable.Lifted` module in [`hashable-1.2.5.0`](http://hackage.haskell.org/package/hashable-1.2.5.0).

**Comment by RyanGlScott** [comment]
@hvr, can this issue be closed?
