### ISSUE TITLE
documentation: Is the hash stable?

### ISSUE THREAD

**Issue by joeyh** [haskell-unordered-containers/hashable#139]
Reading the documentation, I don't know if I can rely on the hash of a given value being the same across different versions of the library, on different OS's, etc.

The example at the top says that hash "foo" == 60853164. But here, it's -3895646688458103097. Checking hashable-1.0.0, it was 112134.

**Comment by tibbe** [comment]
I could swear that used to be documented in the Haddocks but I can't see any documentation there now. The hash is not guaranteed to be stable across library versions, OSes, or architectures. If you need stable hashes e.g. SHA-256, CRC32, etc is a better fit.

**Comment by joeyh** [comment]
Just to be clear, I found the documentation unclear on this, and filed the issue to suggest it be improved.

**Comment by phadej** [comment]
added a note in https://github.com/haskell-unordered-containers/hashable/pull/205
