### ISSUE TITLE
Add info about commonly used hashable types to doc. 

### ISSUE THREAD

**Issue by Haskell-mouse** [haskell-unordered-containers/hashable#163]
I needed to use <Day> type (from time library) as key, but i prefer not to declare instances outside module with type class (or type) definition due to possible confilcts between instances. 

I did not try to find hashable instance, because.... this thought simply did not occur ( 
And i made [PR](https://github.com/tibbe/hashable/pull/161) with added hashable instance for <Day>. 

Oleg Grenrus pointed out to me that there is a hashable-time package and said that maybe would not be useless to add info about common hashable instances to documentation. 

I agree with him, that is why i made this issue.

**Comment by tibbe** [comment]
Is it really feasible to list all possible packages with instances in hashable? We don't do this for e.g. `Eq` and other type classes at the same "level" as `Hashable`. `Hashable` could really have been in base and thinking of it that way is helpful when considering what the library should depend on (e.g. basically nothing).

**Comment by Haskell-mouse** [comment]
I don't think that you should be search for ALL instances int the world )
But if someone find that there is external instance and it can be used oftenly (i think that `Day` can be) as Key, then why not to add it to docs ? Someone else will spend less time for searching/writing his own instance. 

Is it very laborious?

**Comment by tibbe** [comment]
It's not laborious but what principle do you use to decide which ones to document or not? Finding instances ought to be easy, given that orphan instances are a bad idea they should only be in one out of two packages.

**Comment by Haskell-mouse** [comment]
Ok, can i move  instances from hashable-time to this package ? 
I can't move them to the time library, because it can't depend from non-core libraries (

**Comment by hvr** [comment]
Fwiw, I'm for avoiding orphan instances, and given the current state of affairs that `class Hashable` is neither a boot-library (nor in `base`), and as @tibbe already pointed out the previously applied guideline "hashable can depend on boot libs that cannot depend on hashable to avoid orphans",  the desirable & consistent way is in fact to have `hashable` depend on `time` as the benefit outweigh any costs I can think of, IMO.

**Comment by ekmett** [comment]
As an alternative proposal, I wouldn't object strongly to moving `Hashable` into `base`.

This would avoid the whole "which of these two boot packages should depend on the other" issue that would still linger, even if we declared `hashable` a boot package. Then `base-compat` / `base-orphans` could in good conscience clean up missing instances on older versions.

**Comment by phadej** [comment]
As a small update. There is [`hashable-time`](https://hackage.haskell.org/package/hashable-time) package, which provides some `Hashable` instances. However, it will be deprecated, as I'll move `Hashable` instances directly into [`time-compat`](https://hackage.haskell.org/package/time-compat) - a package I created so I can avoid re-installing `time` but I wanted/needed new functionality from `time`.

**Comment by phadej** [comment]
added a note in https://github.com/haskell-unordered-containers/hashable/pull/205
