### ISSUE TITLE
Make functions inlinable

### ISSUE THREAD

**Issue by flip111** [haskell-unordered-containers/hashable#168]
When i compile with `-Wmissed-specialisations` actually indirectly by compiling with `-Weverything` i get the following warnings:

```
src/Main.hs: warning:        
    Could not specialise imported function ‘hashable-1.2.7.0:Data.Hashable.Class.$fHashable(,)_$chashWithSalt’
      when specialising ‘hashable-1.2.7.0:Data.Hashable.Class.$fHashable(,)’
    Probable fix: add INLINABLE pragma on ‘hashable-1.2.7.0:Data.Hashable.Class.$fHashable(,)_$chashWithSalt’
```

I think there is a missed optimization here. The inlinable pragma should be added in the module which export these functions.

**Comment by phadej** [comment]
I'd trust GHC on not exposing some unfolding. Please provide evidence that INLINABLE is in fact beneficial.

**Comment by flip111** [comment]
I can not provide this evidence
