### ISSUE TITLE
It seems like Eq should be a superclass of Hashable

### ISSUE THREAD

**Issue by tysonzero** [haskell-unordered-containers/hashable#180]
`Hashable` specifically mentions `Eq` in the laws of `hashWithSalt`. It seems to me that it should then be a superclass.

It would also simplify the type signature of most uses of `Hashable`.

**Comment by phadej** [comment]
I thought about the same issue recently. Failed to find any counterexample, where `Hashable` would be useful but there are not`Eq` for a type.

In fact, is there other uses of `Hashable` other than `unordered-containers`?

**Comment by hvr** [comment]
Hrm... usually we make superclasses when we can reuse the superclass' impl to infer method impls of the sub-class; but it also makes sense to me to encode laws via an artificial superclass relation

**Comment by tysonzero** [comment]
Personally as a general rule I do not like laws that refer to unrelated classes.

It can lead to situations where adding a valid and lawful instance retroactively makes some other (previously lawful) instance unlawful.

It can also easily be subverted by simply not defining the instance it refers to. Which means that using the typeclass doesn't have any guarantees, unless you also make sure to add the mentioned typeclass to the type signature.

**Comment by phadej** [comment]
I agree with having `Eq` as a super class of `Hashable`. However that is a very major change, so I'll take time to prepare it.
