### ISSUE TITLE
Wrong FNV prime for 64 bit hashes

### ISSUE THREAD

**Issue by rleshchinskiy** [haskell-unordered-containers/hashable#190]
The package uses 16777619 as the prime both in https://github.com/tibbe/hashable/blob/master/cbits/fnv.c#L43 and in https://github.com/tibbe/hashable/blob/master/Data/Hashable/Class.hs#L780 . This is the 32 bit FNV prime, on 64 bit it should use 1099511628211 (https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function).

**Comment by AndrasKovacs** [comment]
I just came here the open the same issue, good to see it already exists.
