### ISSUE TITLE
hashable 1.3 does not install on ghc 9.0.1

### ISSUE THREAD

**Issue by GeorgeCo** [haskell-unordered-containers/hashable#193]

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/4955 and https://github.com/agda/fix-whitespace/issues/13.

**Comment by andreasabel** [comment]
Blocking https://github.com/maoe/lifted-async/issues/32.

**Comment by chris-martin** [comment]
This is package seems like a pretty critical bottleneck for upgrading a lot of others, do we need to add more maintainers?

**Comment by andreasabel** [comment]
> This package seems like a pretty critical bottleneck for upgrading a lot of others, do we need to add more maintainers?

It would be nice if this package could be moved forward quickly.  Maybe PRs #189 and #191 do the job already.

The current maintainers are here: http://hackage.haskell.org/package/hashable/maintainers/, but the last upload by @tibbe was in 2017, the newer uploads in 2018 and 2019 have been done by @hvr.

**Comment by emilypi** [comment]
Just a head's up, `hashable` has 9.0 conflicts upstream that are blocking it from what amounts to a revision of the `base` bounds here. Namely,  `regex-posix`, which is @hvr's package. We'll need to get that unblocked, and then I'll either ping @tibbe directly via email, or we can have a Hackage trustee do it for us (e.g. @Mightybyte). I'm  working hard to get this unblocked, and meeting with relevant folks tomorrow and Monday.

**Comment by phadej** [comment]
Resolved by #195.

I'll make release soon-ish.
