### ISSUE TITLE
Consider dropping INLINE pragma on hashWithSalt

### ISSUE THREAD

**Issue by TeofilC** [haskell-unordered-containers/hashable#210]
Always marking `hashWithSalt` as INLINE can lead to large increases in code size when you have nested data types, especially when using generic instances.

I feel like the burden should be on the user to mark this function as INLINE if they feel it is worthwhile

**Comment by phadej** [comment]
This is speed/size trade-off. I'll need a data backing the claim. I don't see a reason to make a change. (I'm also not sure having big `Hashable` things is a good idea to begin with).

**Comment by phadej** [comment]
the `{-# INLINE hashWithSalt #-}` affects the definitions outside this package, which use generics to derive the instance.

One way to fix that is to introduce a breaking change and force users to use `DerivingVia` and therefore make an explicit choice. Just removing the `{-# INLINE #-}` will change stuff in a subtle and hard to figure out way.

Even I agree in general that it's better to not have `{-# INLINE #-}` unless there is a benchmark justifying that (which we don't, AFAIK), at this point I'm not willing to make a change.

You can write

```haskell
instance Hashable MyIntermediateBigRecord where
    hashWithSalt = genericHashWithSalt
```

and that instance won't have `{-# INLINE #-}`.

**Comment by TeofilC** [comment]
Ah I see! I didn't know that about the behaviour of `INLINE` on default instances. I'll close this in that case. Thanks for you helpful responses!
