### ISSUE TITLE
Support text-1.3 (with UTF8 internal encoding)

### ISSUE THREAD

**Issue by jberryman** [haskell-unordered-containers/hashable#214]
Just a heads up in light of https://github.com/haskell/text/pull/365 

The test suite does not catch that when `hashable` is compiled with above the `Text` instances result in a buffer over-read

**Comment by phadej** [comment]
That's why `hashable` defines an upper bound on `text`. I doubt the internal encoding change will be released as `text-1.2.x`.

**Comment by phadej** [comment]
I renamed the issue. I'll look at it when `text` patch is merged. Others are free to look sooner.
