### ISSUE TITLE
Building on 7.10 gives linker error

### ISSUE THREAD

**Issue by konsumlamm** [haskell-unordered-containers/hashable#221]
Trying to build `hashable-1.3.3.0` with GHC 7.10.3 results in the following error for me:
```
/usr/bin/ld: -r and -pie may not be used together
collect2: error: ld returned 1 exit status
```

### System

I'm running Manjaro (Linux) on x86_64.

### Additional information

I installed GHC via ghcup. My cabal version is 3.4 and the ld version is 2.36.1.
I noticed this while trying to test GHC 7.10 in the CI of `primitive`: https://github.com/haskell/primitive/pull/322.

**Comment by sjakobi** [comment]
This seems related to https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/123. See the suggested workaround in https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/123#note_346066.
