### ISSUE TITLE
v1.3.4.0 doesn't build on 32bit

### ISSUE THREAD

**Issue by gisenmann** [haskell-unordered-containers/hashable#228]
Maybe only these two imports are missing:
~~~
--- LowLevel.hs.orig    2001-09-09 03:46:40.000000000 +0200
+++ LowLevel.hs 2021-10-03 08:50:37.760297876 +0200
@@ -27,4 +27,6 @@
 #if WORD_SIZE_IN_BITS != 64
 import Data.Bits (shiftR)
+import Data.Int (Int32)
+import Data.Word (Word32)
 #endif
~~~

**Comment by hasufell** [comment]
I believe this is what broke it https://github.com/haskell-unordered-containers/hashable/pull/227

@phadej

**Comment by phadej** [comment]
Thanks for the report, uploaded https://hackage.haskell.org/package/hashable-1.3.4.1 hopefully fixing the issue.

**Comment by hasufell** [comment]
> Thanks for the report, uploaded https://hackage.haskell.org/package/hashable-1.3.4.1 hopefully fixing the issue.

builds here

**Comment by phadej** [comment]
@hasufell thanks for the confirmation.

**Comment by sjakobi** [comment]
@phadej Could you add a git tag for the release?

**Comment by phadej** [comment]
@sjakobi done.
