### ISSUE TITLE
rejects ghc-bignum-1.1 from ghc-9.0.2

### ISSUE THREAD

**Issue by hasufell** [haskell-unordered-containers/hashable#240]
https://github.com/haskell-unordered-containers/hashable/blob/c89eb526d0a0633c3192fd3e29be1700f16aa0fe/hashable.cabal#L96-L97

**Comment by phadej** [comment]
https://github.com/haskell-unordered-containers/hashable/pull/239

**Comment by phadej** [comment]
https://hackage.haskell.org/package/hashable-1.4.0.2
