### ISSUE TITLE
hashable doesn't compile in ghc 9.6.1-alpha3

### ISSUE THREAD

**Issue by GeorgeCo** [haskell-unordered-containers/hashable#267]
cabal install hashable --lib
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.8.1.0 supports
'ghc' version < 9.6): /usr/local/bin/ghc is version 9.6.0.20230210
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.8.1.0 supports
'ghc' version < 9.6): /usr/local/bin/ghc is version 9.6.0.20230210
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: base-4.18.0.0/installed-4.18.0.0 (user goal)
[__1] trying: bytestring-0.11.4.0/installed-0.11.4.0 (user goal)
[__2] next goal: hashable (user goal)
[__2] rejecting: hashable-1.4.2.0 (conflict:
base==4.18.0.0/installed-4.18.0.0, hashable => base>=4.10.1.0 && <4.18)
[__2] skipping: hashable-1.4.1.0, hashable-1.4.0.2, hashable-1.4.0.1,
hashable-1.4.0.0, hashable-1.3.5.0, hashable-1.3.4.1, hashable-1.3.4.0,
hashable-1.3.3.0, hashable-1.3.2.0, hashable-1.3.1.0, hashable-1.3.0.0,
hashable-1.2.7.0, hashable-1.2.6.1, hashable-1.2.6.0, hashable-1.2.5.0,
hashable-1.2.4.0, hashable-1.2.3.3, hashable-1.2.3.2, hashable-1.2.3.1,
hashable-1.2.3.0, hashable-1.2.2.0, hashable-1.2.1.0, hashable-1.2.0.10,
hashable-1.2.0.9, hashable-1.2.0.8, hashable-1.2.0.7, hashable-1.2.0.6,
hashable-1.2.0.5, hashable-1.2.0.4, hashable-1.2.0.3, hashable-1.2.0.2,
hashable-1.2.0.1, hashable-1.2.0.0, hashable-1.1.2.5, hashable-1.1.2.4,
hashable-1.1.2.3 (has the same characteristics that caused the previous
version to fail: excludes 'base' version 4.18.0.0)
[__2] rejecting: hashable-1.1.2.2, hashable-1.1.2.1, hashable-1.1.2.0,
hashable-1.1.1.0, hashable-1.1.0.0 (conflict: base =>
ghc-prim==0.10.0/installed-0.10.0, hashable => ghc-prim<0.3)
[__2] rejecting: hashable-1.0.1.1 (conflict:
base==4.18.0.0/installed-4.18.0.0, hashable => base>=4.0 && <4.6)
[__2] skipping: hashable-1.0.1.0 (has the same characteristics that caused the
previous version to fail: excludes 'base' version 4.18.0.0)
[__2] rejecting: hashable-1.0.0 (conflict:
bytestring==0.11.4.0/installed-0.11.4.0, hashable => bytestring>=0.9 && <0.11)
[__2] fail (backjumping, conflict set: base, bytestring, hashable)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, hashable, bytestring

It does compile with --allow-new so perhaps a version bump for base is all that is needed

**Comment by andreasabel** [comment]
This issue can be closed as `hashable`'s bounds have been revised: https://hackage.haskell.org/package/hashable-1.4.2.0/revisions/
