### ISSUE TITLE
(  odd x && odd y) ==> hash (x,y) == hash (negate x, negate y )

### ISSUE THREAD

**Issue by jwaldmann** [haskell-unordered-containers/hashable#270]
this should not happen?
```
ghci> hash (1, -3)
-1099511628210

ghci> hash (-1, 3)
-1099511628210

ghci> checkFor 10000 $ \ (x,y) -> (  odd x && odd y) ==> hash (x,y) == hash (negate x, negate y )
+++ OK, passed 10000 tests.
```

I think it has implications for other types, as in
```
ghci> data T k = L | B (T k) k ( T k) deriving (Eq, Show, Generic)
ghci> instance Hashable k => Hashable (T k)

ghci> hash $ B L 0 (B (B L (-1) L) 1 L) 
-9161394600945770392

ghci> hash $ B L 0 (B (B L 1 L) (-1) L)
-9161394600945770392
```

this is with hashable-1.4.2.0, ghc-9.6.2

**Comment by phadej** [comment]
Interesting. I guess it's not a problem with vanilla FNV1 as it hashes byte at the time, so `-1` something different.

That's unfortunate. I would like to mix-in `Int`s efficiently.

I wonder whether there are hash function with machine integers (Word64) as native input type (instead of single bytes).

**Comment by phadej** [comment]
Could you test the current version 0cfa4fd3ef3baf82b2753db6425de3a1f440fd4b in #270. I added more mixing, but just 4 rounds, not 8.

**Comment by phadej** [comment]
> But the change also applies to every generic instance of Hashable (does it?)

It does as we hash the constructor number. Good point, that can be changed to hash as previously. (I have to see a Generic instance of type with over 65536 constructors to compile).

That said, the exact values of `hash` are not part of the API contract, and we are free to change them freely.  It says it in the docs

> Note: the hash is not guaranteed to be stable across library versions, operating systems or architectures. For stable hashing use named hashes: SHA256, CRC32 etc.

I should add that to the description as well.

**Comment by phadej** [comment]
> it's a nice challenge to find a small collision (for (Int,Int), say) with 2, 4, 8 rounds.

What you mean by small? I guess you want to ask SMT for a counterexample of "there aren't simple bit flip collisions for hash(x,y)"

**Comment by phadej** [comment]
To add to the last, don't spend too much time. I'll investigate how much breakage switching `hashable` to using siphash would cause, and how much performance changes (where hashing `Text` or `ByteString` is what really matters, not tuples or lists of `Int`s - though they shouldn't be too slow either).
