### ISSUE TITLE
using Hashed inside a tuple produces collisions

### ISSUE THREAD

**Issue by jwaldmann** [haskell-unordered-containers/hashable#271]
This should not happen?
```
ghci> hash (1, hashed (0,0))
1099511628211

ghci> hash (0, hashed (1,0))
1099511628211
```
well there's bound to be collisions but I do not expect them for very small arguments.

(note: numbers are nonnegative, so it's not an instance of #270)

I guess the reason for the observed behaviour is a combination of
* `instance .. => Hashable (Hashed a)` ignores the salt (?)
* `instance .. => Hashable (a,b)` needs the salt (for `b`) (?)

The code is abstracted from a real use case where I am hashing trees, where subtrees might be shared,  so I store the hash value in each node, to avoid recomputation (similar to what `Hashed a` does). I am getting collisions when such trees appear in some other structure that has a generic Hashable instance.

What _is_ the contract for `Hashed a`? What is the axiom that connects `hash` and `hashWithSalt`? Is there a way to memoize hash values in a tree structure? If the answer is - "not with Data.Hashable", then that's fine (I guess) but I'd appreciate if this was more clear from the documentation.

**Comment by phadej** [comment]
> instance .. => Hashable (Hashed a) ignores the salt.

It doesn't. It hashes the value, and then mixes that in.

```haskell
Prelude Data.Hashable> hashWithSalt 11 (hashed ('x', 'y'))
126443837249824
Prelude Data.Hashable> hashWithSalt 21 (hashed ('x', 'y'))
119846767487038
```

> What is the axiom that connects hash and hashWithSalt? I

None. They can be mutually defined, but there is no law saying they should be. (`hash @Int = id`, `hashWithSalt` does a bit more)

The `hashWithSalt salt x != hashWithSalt salt (hashed x)` in general

```haskell
Prelude Data.Hashable> hashWithSalt 21 $ hashed ('x', 'y')
119846767487038
Prelude Data.Hashable> hashWithSalt 21 $ ('x', 'y')
20132057908569644
```

---

Here the problem is that `hash (0, 0) = 0`, which is a bug. We do

```haskell
    hash (a1, a2) = hash a1 `hashWithSalt` a2
```

but we probably should just not define `hash` for tuples, so the defaultHash is always used, so it's harder to get all-zeros state.

**Comment by phadej** [comment]
Please try https://github.com/haskell-unordered-containers/hashable/pull/272

**Comment by phadej** [comment]
With https://github.com/haskell-unordered-containers/hashable/pull/273

At least the simple examples seem to differ. I haven't tried QC properties. (Maybe I'll go for four rounds instead of two).

I'll fix CI later today and finish the patches later this week.
