### ISSUE TITLE
Minor release 1.4.3.0 introduces semantic changes

### ISSUE THREAD

**Issue by andreasabel** [haskell-unordered-containers/hashable#277]
The fix of #270 changed the hashing algorithm.  This was released as minor bump 1.4.3.0.  I think it should be released as major bump 1.5.0.0 instead.
The semantic change introduced in #270 leads to observable behaviour changes downstream. E.g. `HashSet.toList` will return elements in a different order when build with `hashable-1.4.3.0` in comparison to `1.4.2.0`.
In the wild:
- https://github.com/agda/agda/issues/6750

Suggested fix (from the perspective of this issue): deprecate 1.4.3.0 and release as 1.5.0.0.

**Comment by phadej** [comment]
> Note: the hash is not guaranteed to be stable across library versions, operating systems or architectures. For stable hashing use named hashes: SHA256, CRC32 etc.
