### ISSUE TITLE
hashable doesn't support filepath-1.5, ghc-9.10 will bump filepath to 1.5

### ISSUE THREAD

**Issue by jwaldmann** [haskell-unordered-containers/hashable#292]
hashable doesn't support filepath-1.5  ( https://github.com/haskell-unordered-containers/hashable/issues/291#issuecomment-1949586983 )

ghc-9.10 will bump filepath to 1.5 ( https://gitlab.haskell.org/ghc/ghc/-/milestones/380)

will this create a conflict?

**Comment by andreasabel** [comment]
Hitting this build error:
```
[3 of 7] Compiling Data.Hashable.Class ( src/Data/Hashable/Class.hs, dist/build/Data/Hashable/Class.o, dist/build/Data/Hashable/Class.dyn_o )

src/Data/Hashable/Class.hs:167:1: error: [GHC-87110]
    Could not load module ‘System.OsString.Internal.Types’.
    It is a member of the hidden package ‘os-string-2.0.2’.
    Perhaps you need to add ‘os-string’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
    |
167 | import System.OsString.Internal.Types (OsString (..), PosixString (..), WindowsString (..))
    | 
```
So, at least dependency `os-string` has to be added, it seems.

**Comment by andreasabel** [comment]
It seems that this is not fixed by `head.hackage`: https://gitlab.haskell.org/ghc/head.hackage/-/issues/100

**Comment by andreasabel** [comment]
Possibly be fixed by:
- #290
