### ISSUE TITLE
Could AES-NI instructions be used for better Int hashes?

### ISSUE THREAD

**Issue by spacekitteh** [haskell-unordered-containers/hashable#295]
It seems like instructions such as AESENC only take 1 or 2 cycles. This would surely result in better hashing than the current `hash = id` definition, and probably better mixing than the current `hashWithSalt` implementation, with similar or better performance.

Has anyone tried this?

C.f. https://github.com/haskell-unordered-containers/hashable/issues/270

**Comment by phadej** [comment]
See #310, people care about portability more than about performance.

Using `AESENC` will be very tricky, GHC has to support it first, otherwise the overheads will most-likely kill any potential benefits.
