### ISSUE TITLE
arch-native defaults to True which is dangerous

### ISSUE THREAD

**Issue by TerrorJack** [haskell-unordered-containers/hashable#308]
It's appreciated that the caveat of `arch-native` (creating non-portable binary due to `-march=native`) is documented and visible on the hackage page. But IMHO this is still dangerous, because downstream project authors may not audit all their dependency upgrades, and this looks incredibly likely to sneak into downstream build plans and making downstream CI pipelines produce binaries that crash at runtime on machines with CPUs older than GH action runners.

**Comment by phadej** [comment]
But if `arch-native` is not enabled by default, no-one would notice it. and that leaves quite significant performance boost on the table.

It's a trade-off, and in perfect world the whole tooling (`Cabal`, GHC etc) would support `-march` (with `native` as a choice, and I'd argue it should be default; Haskell is more often build for local stuff - the distribution use-case is more involved, and people usually know what they are doing). Then packages won't need to use package flags for that at all.

There are also plenty of packages on Hackage which have flags like `sse4`, and I honestly never look them nor enable them.

**Comment by phadej** [comment]
I'll add, that `cabal-install` doesn't even support building for distribution of the box. You need to know a bit of what it does to make a distributable binary. (And e.g. audit your dependencies that they don't use data-files, etc). I'm not mentioning static linkage, etc.

And figuring out you need to turn a package flag is a lot less work then e.g. fixing issues like https://github.com/ndmitchell/hlint/issues/1533, which is arguably the same problem: the binary for distribution is not built to be as widely usable as it could.

**Comment by matil019** [comment]
I was bitten hard by this change. It took quite some time to reach here from my server written with Servant crashing with an unfamiliar message `Illegal instruction (core dumped)` (a.k.a. SIGILL).
FYI I was compiling the server on a faster machine to run on a slower machine (that had an older CPU).

At least I'm relieved to know that there is a "quite significant performance boost" which could justify the tradeoff. But I wish the change would have been emphasized much more, for example by incrementing the major version number.
