### ISSUE TITLE
hashable 1.4.6.0 build failure

### ISSUE THREAD

**Issue by chenrui333** [haskell-unordered-containers/hashable#310]
👋 while trying to update some brew formulae, [ormolu](https://github.com/Homebrew/homebrew-core/pull/174372) and [fourmolu](https://github.com/Homebrew/homebrew-core/pull/174344), seeing some build failures as below:

```
  Building library for hashable-1.4.6.0..
  [ 1 of 10] Compiling Data.Hashable.FFI ( src/Data/Hashable/FFI.hs, dist/build/Data/Hashable/FFI.o, dist/build/Data/Hashable/FFI.dyn_o )
  clang: error: the clang compiler does not support '-march=native'
```

**Comment by phadej** [comment]
According to https://stackoverflow.com/a/72597669 `clang-15` supports `-march=native`. Otherwise turn `arch-native` flag off.

**Comment by chenrui333** [comment]
make sense, looks like only happens for monterey-arm build.

**Comment by hasufell** [comment]
Why is this flag on by default if it:

* breaks with some compilers
* makes binaries less portable

**Comment by Mikolaj** [comment]
We are just releasing cabal 3.12.1.0. How do we prevent this happening to users of our binaries?

**Comment by Kleidukos** [comment]
@phadej Hi, may I ask you if you could perhaps do a release of `hashable` without the non-portable CFLAG? :)

**Comment by soulomoon** [comment]
Relating to https://github.com/haskell-unordered-containers/hashable/issues/308

**Comment by phadej** [comment]
Ok, so if you care about performance of your application, you will profile your application, and enable the flag in the future.

I'll turn it off. For the record, on my machine you lose 20% of hash performance, which for hash intensive things will matter. (And if your application is not hash intensive, don't use `hashable`/`unordered-containers`, use ordinary `containers`). 

```
Benchmark              without   with            
hash/Text/strict/11    1.481e-8  1.289e-8 -12.95%
hash/Text/strict/128   0.319e-7  0.263e-7 -17.73%
hash/Text/strict/2^20  2.220e-4  1.252e-4 -43.61%
hash/Text/strict/40    1.934e-8  1.714e-8 -11.37%
hash/Text/strict/5     1.194e-8  0.995e-8 -16.64%
hash/Text/strict/512   0.778e-7  0.649e-7 -16.62%
hash/Text/strict/8     1.215e-8  0.983e-8 -19.09%
Geometric mean         0.810e-7  0.644e-7 -20.47%
```

**Comment by wz1000** [comment]
I think it may also be a good idea to mark the affected versions of hashable as deprecated on hackage to prevent them from being inadvertently pulled into any build plans in the future.

**Comment by phadej** [comment]
> deprecated on hackage to prevent them from being inadvertently pulled into

This is common misconception. Deprecating on the Hackage is only a *soft* constraint. `cabal-install` will violate it if forced. And if there are no tight constraints, it won't not pick the later version.

**Comment by hasufell** [comment]
> > deprecated on hackage to prevent them from being inadvertently pulled into
> 
> This is common misconception. Deprecating on the Hackage is only a _soft_ constraint. `cabal-install` will violate it if forced. And if there are no tight constraints, it won't not pick the later version. So deprecation essentially only changes the color of the version on the Hackage page.

You can change the base dependency to `base < 0`, which is sometimes done to make a package non-installable: https://hackage.haskell.org/package/unix-2.8.2.0/revisions/

**Comment by phadej** [comment]
@hasufell I know, but that is not *deprecation*.

**Comment by hasufell** [comment]
> @hasufell I know, but that is not _marking as deprecated_ it's _making a package version uninstallable with an unsatisfiable constraint trick_

Correct. As Zubin pointed out the motivation is: 

> to prevent them from being inadvertently pulled into any build plans in the future

This can be achieved with said trick.

**Comment by hasufell** [comment]
[Remote cabal files](https://cabal.readthedocs.io/en/stable/cabal-project-description-file.html#conditionals-and-imports) could also be used to create a set of constraints that try to achieve maximum performance (`text +simdutf` and `hashable +arch-native` for example).

This constraint set could then be maintained centrally and also serve as documentation.
