### ISSUE TITLE
Support GHC 9.12 (base-4.21)

### ISSUE THREAD

**Issue by andreasabel** [haskell-unordered-containers/hashable#312]
> [__3] rejecting: base-4.21.0.0/installed-cc73 (conflict: hashable => base>=4.18.0.0 && <4.21)

**Comment by andreasabel** [comment]
And now it is Christmas,
and what have you done?
🎄 🎁 
_Another year over
And a new one's just begun
And so this is Christmas
I hope you have fun
The near and the dear one
The old and the young_

**Comment by phadej** [comment]
9.12.1 is not yet in `ghcup`, and as there are indeed Christmas/New Year festives coming, I doubt I will spend them on Haskell. The major compiler release a week before holidays is just not nice for library maintainers (sure it's nice for people to get new toy to play with; but for me each GHC release is more of a burden than a joy).

I probably will take a look at `hashable` and `splitmix`, but don't me expect to deal with similar issues this year.

**Comment by phadej** [comment]
And pinging on issues, or opening new ones, won't make me do anything faster,; probably the opposite if anything. This comment is especially for @erikd. I do notice when GHC is released, thanks.

**Comment by hasufell** [comment]
> 9.12.1 is not yet in ghcup vanilla channel

https://github.com/haskell/ghcup-metadata/pull/270

**Comment by phadej** [comment]
@hasufell thanks, but I actually meant the default channel, not the vanilla. I'm not in hurry, and I appreciate you double checking the bindists (so we, downstream, don't need to wonder if something doesnt work)

**Comment by hasufell** [comment]
> @hasufell thanks, but I actually meant the default channel, not the vanilla. I'm not in hurry, and I appreciate you double checking the bindists (so we, downstream, don't need to wonder if something doesnt work)

https://github.com/haskell/ghcup-metadata/pull/272
