### ISSUE TITLE
Documentation about minimal definition of Hashable is contradictory

### ISSUE THREAD

**Issue by andreasabel** [haskell-unordered-containers/hashable#98]
From https://hackage.haskell.org/package/hashable-1.2.3.2/docs/Data-Hashable.html

`class Hashable a where`
  The class of types that can be converted to a hash value.
  Minimal implementation: hashWithSalt.
  Minimal complete definition
    Nothing

**Comment by tibbe** [comment]
This is a bug in GHC that has something to do with default signatures. Even when I put an explicit `MINIMAL` pragma GHC claims that the minimal complete definition is "nothing".

**Comment by RyanGlScott** [comment]
Interesting, this doesn't appear to be the case any more, at least with GHC 7.10.3 / `haddock-2.16.1`. If I make this change:

```diff
diff --git a/Data/Hashable/Class.hs b/Data/Hashable/Class.hs
index 5ab3cc4..53dd98a 100644
--- a/Data/Hashable/Class.hs
+++ b/Data/Hashable/Class.hs
@@ -155,6 +155,10 @@ defaultSalt = 0x087fc72c
 --
 -- Minimal implementation: 'hashWithSalt'.
 class Hashable a where
+#if __GLASGOW_HASKELL__ >= 708
+    {-# MINIMAL hashWithSalt #-}
+#endif
+
     -- | Return a hash value for the argument, using the given salt.
     --
     -- The general contract of 'hashWithSalt' is:
```

and run `cabal haddock`, this is what I get:

![hashable_minimal](https://cloud.githubusercontent.com/assets/2364661/19418622/b4c8ce52-9395-11e6-8e96-0e202b863954.png)

**Comment by treeowl** [comment]
@RyanGlScott, these days Haddock can figure it out on its own, without a `MINIMAL` pragma. I don't think we actually *want* such a pragma, since we (now) have a generic implementation of `hashWithSalt`. Time to close this ticket.
